# Generated by Django 4.2.5 on 2023-11-01 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/customize")),
                ("name_on_cover", models.CharField(default=None, max_length=100)),
                ("quantity", models.IntegerField(default=1)),
                ("ammount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("phone", models.CharField(default=None, max_length=10)),
                ("phone_model", models.CharField(default=None, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
